### PR TITLE
Restyle new pages + fix empty match/team key

### PR DESCRIPTION
**Pull request by 0xda157**
- [x] Switch to brand colors for tele and auto
- [x] Restyle postmatch
- [x] Fix timeline animation (plz test on safari)
- [x] Restyle homepage buttons to closer match other buttons
- [x] Check that match/team key aren't empty on manual scouting
- [x] Restyle leave queue button

### CODE REVIEW

**Review by azaleacolburn — CHANGES_REQUESTED** [review]
Naur, I liked my big oval buttons (jk).
There's an issue where the dropdown menu is super small on arc
Screenshot 2024-12-09 at 8 31 05 PM
Also, could we get some more padding on the postmatch page, it looks kinda cramped.

Unrelated (this is my fault), but could you add a back button in the manual scout menu
Otherwise, great work

**Comment by 0xda157** [comment]
> There's an issue where the dropdown menu is super small on arc Screenshot 2024-12-09 at 8 31 05 PM

This seems like a arc skill issue, can you test it in chrome and safari. Also test if this html by itself looks correct on arc plz:
```html
<!doctype html>
<body>
  <select name="color">
    <option selected value="">Select a color</option>
    <option value="blue">Blue</option>
    <option value="red">Red</option>
  </select>
</body>
```

**Comment by 0xda157** [comment]
> but could you add a back button in the manual scout menu

Can't the user just go back to previous page using their web browser controls

**Comment by azaleacolburn** [comment]
> > but could you add a back button in the manual scout menu
> 
> Can't the user just go back to previous page using their web browser controls

They _can_, they shouldn't have to though

**Review by azaleacolburn — APPROVED** [review]
lgtm

**Pull request merged**
